// frontend-vue/src/components/Sidebar.vue
<template>
  <div id="menu">
    <div class="pure-menu">
      <router-link to="/" class="pure-menu-heading">Company</router-link>

      <ul class="pure-menu-list">
        <li class="pure-menu-item">
          <router-link to="/" class="pure-menu-link">Home</router-link>
        </li>

        <li class="pure-menu-item">
          <router-link to="autor" class="pure-menu-link">Autor</router-link>
        </li>

        <li class="pure-menu-item">
          <router-link to="livro" class="pure-menu-link">Livro</router-link>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  name: "sidebar"
};
</script>

<style>
</style>

// frontend-react/src/components/SideBar/index.js
import React from 'react';
import { Link } from 'react-router-dom';

export default function SideBar() {
    return (
        <>
            <div id="menu">
                <div className="pure-menu">
                    <Link to="/" className="pure-menu-heading">Alura ReactJS</Link>

                    <ul className="pure-menu-list">
                        <li className="pure-menu-item">
                            <Link to="/" className="pure-menu-link">Home</Link>
                        </li>

                        <li className="pure-menu-item">
                            <Link to="/autores" className="pure-menu-link">Autores</Link>
                        </li>

                        <li className="pure-menu-item">
                            <Link to="/livros" className="pure-menu-link">Livros</Link>
                        </li>
                    </ul>
                </div>
            </div>
        </>
    );
}
