// frontend-react/src/pages/Home/index.js
import React from 'react';

export default function Home() {
    return (
        <>
            <div className="header">
                <h1>Bem vindo ao sistema</h1>
                <h2>Este sistema foi feito com ReactJS</h2>
            </div>

            <div className="content">
            </div>
        </>
    );
}

// frontend-vue/src/views/Home.vue
<template>
    <div>
        <div class="header">
            <h1>Bem vindo ao sistema</h1>
            <h2>Este sistema foi feito com VueJS</h2>
        </div>
        <div class="content"></div>
    </div>
</template>

<script>
export default {
    name: "Home"
};
</script>

<style scoped>

</style>
